controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    action_monitor_rate: 10.0
    allow_partial_joints_goal: true
    set_last_command_interface_value_as_state_on_activation: false

position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint




